sudo: required
services:
  - docker
language: ruby
notifications:
  slack:
    on_success: always
  email: false
script:
  - docker build . --compress -f docker/3.0/Dockerfile -t ci/docker-phaser:3.0
  - docker rmi ci/docker-phaser:3.0
  - docker build . --compress -f docker/3.0.0/Dockerfile -t ci/docker-phaser:3.0.0
  - docker rmi ci/docker-phaser:3.0.0
  - docker build . --compress -f docker/3.1/Dockerfile -t ci/docker-phaser:3.1
  - docker rmi ci/docker-phaser:3.1
  - docker build . --compress -f docker/3.1.0/Dockerfile -t ci/docker-phaser:3.1.0
  - docker rmi ci/docker-phaser:3.1.0
  - docker build . --compress -f docker/3.1.1/Dockerfile -t ci/docker-phaser:3.1.1
  - docker rmi ci/docker-phaser:3.1.1
  - docker build . --compress -f docker/3.1.2/Dockerfile -t ci/docker-phaser:3.1.2
  - docker rmi ci/docker-phaser:3.1.2
  - docker build . --compress -f docker/3.2/Dockerfile -t ci/docker-phaser:3.2
  - docker rmi ci/docker-phaser:3.2
  - docker build . --compress -f docker/3.2.0/Dockerfile -t ci/docker-phaser:3.2.0
  - docker rmi ci/docker-phaser:3.2.0
  - docker build . --compress -f docker/3.2.1/Dockerfile -t ci/docker-phaser:3.2.1
  - docker rmi ci/docker-phaser:3.2.1
  - docker build . --compress -f docker/3.3/Dockerfile -t ci/docker-phaser:3.3
  - docker rmi ci/docker-phaser:3.3
  - docker build . --compress -f docker/3.3.0/Dockerfile -t ci/docker-phaser:3.3.0
  - docker rmi ci/docker-phaser:3.3.0
  - docker build . --compress -f docker/3.4/Dockerfile -t ci/docker-phaser:3.4
  - docker rmi ci/docker-phaser:3.4
  - docker build . --compress -f docker/3.4.0/Dockerfile -t ci/docker-phaser:3.4.0
  - docker rmi ci/docker-phaser:3.4.0
  - docker build . --compress -f docker/3.5/Dockerfile -t ci/docker-phaser:3.5
  - docker rmi ci/docker-phaser:3.5
  - docker build . --compress -f docker/3.5.0/Dockerfile -t ci/docker-phaser:3.5.0
  - docker rmi ci/docker-phaser:3.5.0
  - docker build . --compress -f docker/3.5.1/Dockerfile -t ci/docker-phaser:3.5.1
  - docker rmi ci/docker-phaser:3.5.1
  - docker build . --compress -f docker/3.6/Dockerfile -t ci/docker-phaser:3.6
  - docker rmi ci/docker-phaser:3.6
  - docker build . --compress -f docker/3.6.0/Dockerfile -t ci/docker-phaser:3.6.0
  - docker rmi ci/docker-phaser:3.6.0
  - docker build . --compress -f docker/3.6.1/Dockerfile -t ci/docker-phaser:3.6.1
  - docker rmi ci/docker-phaser:3.6.1
  - docker build . --compress -f docker/3.7/Dockerfile -t ci/docker-phaser:3.7
  - docker rmi ci/docker-phaser:3.7
  - docker build . --compress -f docker/3.7.0/Dockerfile -t ci/docker-phaser:3.7.0
  - docker rmi ci/docker-phaser:3.7.0
  - docker build . --compress -f docker/3.7.1/Dockerfile -t ci/docker-phaser:3.7.1
  - docker rmi ci/docker-phaser:3.7.1
  - docker build . --compress -f docker/3.8/Dockerfile -t ci/docker-phaser:3.8
  - docker rmi ci/docker-phaser:3.8
  - docker build . --compress -f docker/3.8.0/Dockerfile -t ci/docker-phaser:3.8.0
  - docker rmi ci/docker-phaser:3.8.0
  - docker build . --compress -f docker/3.9/Dockerfile -t ci/docker-phaser:3.9
  - docker rmi ci/docker-phaser:3.9
  - docker build . --compress -f docker/3.9.0/Dockerfile -t ci/docker-phaser:3.9.0
  - docker rmi ci/docker-phaser:3.9.0
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
